### ISSUE TITLE
Formatear tabs de descripción y transporte

### ISSUE THREAD

**Issue by jmloyola** [TallerArgentinoCC/TallerArgentinoCC.github.io#12]
Aplicar formato a los tabs de [descripción](https://tallerargentinocc.github.io/descripcion.html) y [transporte](https://tallerargentinocc.github.io/transporte.html) de la página web.
Por ejemplo:
- enumerar las actividades científicas,
- enumerar las líneas de colectivo,
- colocar negrita o enfatizado a algunas palabras claves. Similar a lo que se hizo en el [pdf para sponsors](https://github.com/TallerArgentinoCC/TallerArgentinoCC.github.io/blob/master/docs/Sponsors%20-%20TAC2.pdf).

**Comment by HoracioNakama** [comment]
No me parecia que fuera bueno enumerarlas, pero le agregue viñetas para diferenciarla mejor del resto del texto.
Y estaba bueno lo de enfatizar las palabras claves, por ahora solo les cambie de color.
