### ISSUE TITLE
agregar logo de aerolineas 

### ISSUE THREAD

**Issue by aloctavodia** [TallerArgentinoCC/TallerArgentinoCC.github.io#14]
hay que agregar el logo a la página, el texto se puede adaptar de [acá](https://pydata.org/sanluis2017/) desde donde dice "Aerolineas Argentinas es el transportador oficial..."

**Comment by HoracioNakama** [comment]
Agregue el logo, también como "Transportador oficial" en el index y le agregue el texto "Aerolíneas Argentinas como Transportador Oficial no es responsable de la organización, ejecución o de cualquier otra actividad relacionada con la..."
