### ISSUE TITLE
agregar link/logo de Twitter 

### ISSUE THREAD

**Issue by aloctavodia** [TallerArgentinoCC/TallerArgentinoCC.github.io#24]
Quizá el header es buena idea así está presente en todas las sub-páginas

**Comment by HoracioNakama** [comment]
El menú me parecía muy largo y se veía superposición

Quite el Menú Inicio, no es gran perdida porque TAC2 ya tiene link a inicio, y acorté "Codigo de conducta" a "Conducta"

Y agregué el logo de twitter
