### ISSUE TITLE
En el formulario de inscripción solamente hay lugar para un autor... ¿puede ampliarse?

### ISSUE THREAD

**Issue by gefero** [TallerArgentinoCC/TallerArgentinoCC.github.io#26]

**Comment by aloctavodia** [comment]
no, sep. pero el nombre corresponde al autor que presenta el trabajo,no?

**Comment by gefero** [comment]
Correcto... pero si es más de un autor?
-----------------------------------
Germán Rosati
https://gefero.github.io
-----------------------------------
