### ISSUE TITLE
titulo TAC^2 con diferente tamaño en Hospedaje y Cronograma

### ISSUE THREAD

**Issue by curiale** [TallerArgentinoCC/TallerArgentinoCC.github.io#30]
Aparentemente el tamaño del título TAC^2 se ve más chico en las secciones de Hospedaje y Cronograma. Esto fue comprobado con Safari y Chrome para osx. Mire un poco el código fuente y los estilos parecen estar bien.

**Comment by aloctavodia** [comment]
En firefox/ubuntu se ve bien. Pruebo en algun otro dentro de un rato
