### ISSUE TITLE
crear cuentas en redes sociales

### ISSUE THREAD

**Issue by jmloyola** [TallerArgentinoCC/TallerArgentinoCC.github.io#6]
Crear las cuentas en redes sociales para divulgación del evento.
Me parece que twitter sería la mejor opción.

**Comment by aloctavodia** [comment]
Acuerdo, yo soy malisimo poniendole onda a los tweets. Alguien se ofrece? Tb puede ser una cuenta compartida entre un par de personas...

**Comment by jmloyola** [comment]
Se podría crear una cuenta en twitter con el mail institucional nuevo de tacc y manejar de a varios la cuenta. ¿Que les parece?
El identificador de usuario puede ser _tacc2019_ (está disponible, por ahora)

**Comment by aloctavodia** [comment]
mejor tacc, por si la cosa sigue, pasamos la cuenta

**Comment by aloctavodia** [comment]
me obliga a asociarle un número de teléfono...

**Comment by jmloyola** [comment]
Pasa que ya está [ocupado ese nombre de usuario](https://twitter.com/TACC)

**Comment by jmloyola** [comment]
¿No le podes poner que te registras con e-mail en lugar de número de teléfono?

**Comment by aloctavodia** [comment]
Lista la cuenta en twitter `tacc2019`

**Comment by aloctavodia** [comment]
Vamos a crear algo más que twitter?

**Comment by aloctavodia** [comment]
Voy a cerrar esto, tenemos una cuenta de twitter y ya nos parece demasiado :-( quizá se podría agregar una de telegram ....
